CREATE TABLE PRODUCT 
   (	
   	ID BIGINT NOT NULL PRIMARY KEY, 
	NAME VARCHAR(100) DEFAULT NULL, 
	BRAND VARCHAR(100) DEFAULT NULL, 
	TYPE VARCHAR(50), 
	PRICE INT,
	WARRANTYYEARS INT,
	AVAILABLE BOOLEAN,
	DESCRIPTION VARCHAR(4000) DEFAULT NULL);