(function(){jQuery(document).ready(function(){jQuery("#wp-admin-bar-tdb_template_builder_disabled a").click(function(a){a.preventDefault();alert("Please select tagDiv Builder Template from the theme panel or set a default template. The current page/post uses a template that is not editable.")});jQuery("#wp-admin-bar-new-tdb_templates").hide()})})();var tdbMenu={};
(function(){tdbMenu={items:[],item:function(){this.blockUid="";this._outsideClickArea=this._mainMenu=this._itemsWithSubmenu=null;this._outsideClickExcludedAreas="";this._openMenuClass="tdb-hover";this._openMenuBodyClass="tdb-open-menu";this._is_initialized=this.isMegaMenuParentPos=this.isMegaMenuFull=this.inComposer=!1},init:function(){tdbMenu.items=[]},_initialize_item:function(a){if(!0!==a._is_initialized){tdbMenu._setHover(a);var b=0<jQuery("."+a.blockUid+"_rand").parents(".td-header-template-wrap").length;
window.tdb_globals.isAjax?b||(a.isMegaMenuFull&&tdbMenu.megaMenuFull(a,a.inComposer),a.isMegaMenuParentPos&&tdbMenu.megaMenuParentPos(a,a.inComposer)):(a.isMegaMenuFull&&tdbMenu.megaMenuFull(a,a.inComposer),a.isMegaMenuParentPos&&tdbMenu.megaMenuParentPos(a,a.inComposer));a._is_initialized=!0}},addItem:function(a){if("undefined"===typeof a.blockUid)throw"item.blockUid is not defined";tdbMenu.items.push(a);tdbMenu._initialize_item(a)},deleteItem:function(a){for(var b=0;b<tdbMenu.items.length;b++)if(tdbMenu.items[b].blockUid===
a)return tdbMenu.items.splice(b,1),!0;return!1},megaMenuFull:function(a,b){function e(){k=f.find(".tdb-menu .tdb-mega-menu ul");d=-c.left+"px";0<k.length&&k.attr("style","left:"+d+"; width: "+jQuery("body").outerWidth()+"px !important")}var f=a.jqueryObj,c,h,d,k;jQuery(window).resize(function(){setTimeout(function(){c=f.offset();h=c.left;e();b&&setInterval(function(){c=f.offset();c.left!==h&&(e(),h=c.left)},1E3)},500)});jQuery(window).resize()},megaMenuParentPos:function(a,b){function e(){d.show();
d.each(function(){jQuery(this).css("left","");k=jQuery(this).offset();l=k.left;0>l?jQuery(this).offset({left:0}):(g=jQuery(window).width()-(l+jQuery(this).outerWidth()),0>g&&jQuery(this).offset({left:jQuery(window).width()-jQuery(this).outerWidth()}))});d.hide()}var f=a.jqueryObj,c,h,d=f.find(".tdb-menu .tdb-mega-menu ul"),k,l,g;setTimeout(function(){jQuery(window).resize(function(){c=f.offset();h=c.left;e();b&&setInterval(function(){c=f.offset();c.left!==h&&(e(),h=c.left)},1E3)});jQuery(window).resize()},
60)},_getSubmenuPosition:function(a){var b=jQuery(window).width();a=a.children("ul").first();if(0<a.length){var e=a.offset().left+a.width();e>b&&(a.parent().parent().hasClass("tdb-menu")?a.css("left","-"+(e-b)+"px"):a.addClass("reversed").css("left","-"+(a.width()+0)+"px"))}},_getMouseAngleDirection:function(a,b,e,f){return Math.atan2(e-a,f-b)/Math.PI*180},_setHover:function(a){var b=a.jqueryObj.find(".tdb-menu");b.supersubs({minWidth:10,maxWidth:20,extraWidth:1,applyMin:!0});var e=b.find(".menu-item-has-children > a, .tdb-mega-menu > a");
e.parent().find("ul").first().css("display","none");if(tdDetect.isTouchDevice)jQuery(document).on("touchstart","body",function(b){var d=e.parent(),c=jQuery("body");c.hasClass(a._openMenuBodyClass)&&!d.is(b.target)&&0===d.has(b.target).length&&(d.removeClass(a._openMenuClass),d.children("ul").hide(),c.removeClass(a._openMenuBodyClass))}),e.on("touchstart",function(b){b.preventDefault();b.stopPropagation();var d=jQuery(this);b=d.parent();var c=jQuery("body");b.hasClass(a._openMenuClass)?null!==d.attr("href")&&
"#"!==d.attr("href")?window.location.href=d.attr("href"):((b.parent().hasClass("tdb-menu")||b.parent().hasClass("top-header-menu"))&&c.removeClass(a._openMenuBodyClass),b.removeClass(a._openMenuClass),b.find("ul").hide(),b.find("li").removeClass(a._openMenuClass)):(b.parent().hasClass("tdb-menu")||b.parent().hasClass("top-header-menu")?(e.parent().removeClass(a._openMenuClass),e.parent().children("ul").hide()):(d=b.siblings(),d.removeClass(a._openMenuClass),d.find("ul").hide(),d.find("li").removeClass(a._openMenuClass)),
b.addClass(a._openMenuClass),b.children("ul").show(),tdbMenu._getSubmenuPosition(b),c.addClass(a._openMenuBodyClass))});else{var f={},c,h=!0;b.on("mouseleave",function(){e.parent().removeClass(a._openMenuClass);e.parent().children("ul").hide();f={}});b.find(".menu-item").hover(function(){var b=jQuery(this),k="",l,g;if(b.hasClass("menu-item-has-children")||b.hasClass("tdb-mega-menu"))if(b.parent().hasClass("tdb-menu"))if(jQuery.isEmptyObject(f))b.addClass(a._openMenuClass),b.children("ul").show(),
f=b;else{if(b[0]!==f[0]){var m=g=l=0;var n=null;!0===h&&(h=!1,c=setTimeout(function(){e.parent().removeClass(a._openMenuClass);e.parent().children("ul").hide();b.addClass(a._openMenuClass);b.children("ul").show();f=b},400));b.on("mousemove",function(d){5<=l?(l=0,n=tdbMenu._getMouseAngleDirection(g,m,d.pageX,d.pageY),g=d.pageX,m=d.pageY):(l++,0===g&&0===m&&(g=d.pageX,m=d.pageY));null!==n&&(85<n||-85>n)&&(e.parent().removeClass(a._openMenuClass),e.parent().children("ul").hide(),b.addClass(a._openMenuClass),
b.children("ul").show(),b.off("mousemove"),clearTimeout(c),h=!0,f=b)})}}else k=b.siblings(),k.removeClass(a._openMenuClass),k.find("ul").hide(),k.find("li").removeClass(a._openMenuClass),b.addClass(a._openMenuClass),b.children("ul").show(),tdbMenu._getSubmenuPosition(b);else b.parent().hasClass("tdb-menu")?jQuery.isEmptyObject(f)||(m=g=l=0,n=null,!0===h&&(h=!1,c=setTimeout(function(){e.parent().removeClass(a._openMenuClass);e.parent().children("ul").hide();f={}},400)),b.on("mousemove",function(d){5<=
l?(l=0,n=tdbMenu._getMouseAngleDirection(g,m,d.pageX,d.pageY),g=d.pageX,m=d.pageY):(l++,0===g&&0===m&&(g=d.pageX,m=d.pageY));null!==n&&(85<n||-85>n)&&(e.parent().removeClass(a._openMenuClass),e.parent().children("ul").hide(),b.off("mousemove"),clearTimeout(c),h=!0,f={})})):(f=b.parent(),k=b.siblings(),k.removeClass(a._openMenuClass),k.find("ul").hide(),k.find("li").removeClass(a._openMenuClass))},function(){var a=jQuery(this);!1===h&&(clearTimeout(c),h=!0);a.off("mousemove")})}},unsetHover:function(a){null!==
a._itemsWithSubmenu&&a._itemsWithSubmenu.off();null!==a._outsideClickArea&&a._outsideClickArea.off()}}})();var tdbMenuItemPullDown={};
(function(){tdbMenuItemPullDown={init:function(){setTimeout(function(){jQuery(".tdb-menu-items-pulldown").each(function(a,b){var e=jQuery(b),f=e.parent().attr("id"),c=jQuery("."+f+"_rand"),h="";"none"!==c.css("max-width")&&(h=c.css("max-width"));if(c.hasClass("tdb-menu-items-in-more")){var d=e.find(".tdb-menu:first"),k=d.parents(".tdb-menu-items-pulldown:first"),l=[],g=new tdPullDown.item;if(void 0!==c.css("display")&&"inline-block"===c.css("display")){var m=c.closest(".vc_column_container");k=m;
c="";c=0!==m.find(".tdc-elements").length?".tdc-elements":".wpb_wrapper";m.find(c+" > .td_block_wrap").each(function(){var a=.9*m.outerWidth(!0),b=jQuery(this).outerWidth(!0);if(jQuery(this).data("td-block-uid")!==f)if(b<a)l.push(jQuery(this));else return!1})}g.blockUid=f;g.horizontal_jquery_obj=d;g.vertical_jquery_obj=e.find(".tdb-menu-items-dropdown:first");g.horizontal_element_css_class="tdb-menu-item-button";g.horizontal_no_items_css_class="tdb-menu-items-empty";g.container_jquery_obj=k;g.horizontal_max_width=
h;g.excluded_jquery_elements=l;tdPullDown.add_item(g)}})},50)}}})();jQuery().ready(function(){tdbMenu.init()});jQuery(window).load(function(){tdbMenuItemPullDown.init()});var tdbSearch={};
(function(){tdbSearch={items:[],init:function(){tdbSearch.items=[]},item:function(){this.jqueryObj=this.blockAtts=this.blockUid=void 0;this._is_search_open=!1;this._last_request_results_count=this._current_selection_index=0;this._first_down_up=!0;this._resultsLimit=void 0;this._openSearchFormClass="";this._is_initialized=!1},_initialize_item:function(a){!0!==a._is_initialized&&(jQuery(document).on("click",function(b){jQuery("."+a.blockUid+"_rand .tdb-head-search-form-input").get(0)!==b.target&&!0===
a._is_search_open&&tdbSearch.hide_search_box(a)}),a.jqueryObj.find(".tdb-head-search-btn").on("click",function(b){b.preventDefault();b.stopPropagation();!0===a._is_search_open?tdbSearch.hide_search_box(a):tdbSearch.show_search_box(a)}),a.jqueryObj.find(".tdb-head-search-form-input").keydown(function(b){if(b.which&&39===b.which||b.keyCode&&39===b.keyCode||b.which&&37===b.which||b.keyCode&&37===b.keyCode)tdbSearch.set_input_focus(a);else{if(b.which&&13===b.which||b.keyCode&&13===b.keyCode)return b=
a.jqueryObj.find(".tdb-aj-cur-element"),0<b.length?window.location=b.find(".entry-title a").attr("href"):jQuery(this).parent().parent().submit(),!1;if(b.which&&40===b.which||b.keyCode&&40===b.keyCode)return tdbSearch.move_prompt_down(a),!1;if(b.which&&38===b.which||b.keyCode&&38===b.keyCode)return tdbSearch.move_prompt_up(a),!1;(b.which&&8===b.which||b.keyCode&&8===b.keyCode)&&1===jQuery(this).val().length&&a.jqueryObj.find(".tdb-aj-search").empty();tdbSearch.set_input_focus(a);setTimeout(function(){tdbSearch.do_ajax_call(a)},
100);return!0}}),a._is_initialized=!0)},addItem:function(a){if("undefined"===typeof a.blockUid)throw"item.blockUid is not defined";tdbSearch.items.push(a);tdbSearch._initialize_item(a)},deleteItem:function(a){for(var b=0;b<tdbSearch.items.length;b++)if(tdbSearch.items[b].blockUid===a)return tdbSearch.items.splice(b,1),!0;return!1},show_search_box:function(a){a.jqueryObj.find(".tdb-drop-down-search").addClass(a._openSearchFormClass);!0!==tdDetect.isIos&&setTimeout(function(){document.querySelector("."+
a.blockUid+"_rand .tdb-head-search-form-input").focus()},200);a._is_search_open=!0},hide_search_box:function(a){a.jqueryObj.find(".tdb-drop-down-search").removeClass(a._openSearchFormClass);a._is_search_open=!1},move_prompt_up:function(a){!0===a._first_down_up?(a._first_down_up=!1,0===a._current_selection_index?a._current_selection_index=a._last_request_results_count-1:a._current_selection_index--):0===a._current_selection_index?a._current_selection_index=a._last_request_results_count:a._current_selection_index--;
tdbSearch._repaintCurrentElement(a)},move_prompt_down:function(a){!0===a._first_down_up?a._first_down_up=!1:a._current_selection_index===a._last_request_results_count?a._current_selection_index=0:a._current_selection_index++;tdbSearch._repaintCurrentElement(a)},set_input_focus:function(a){a._current_selection_index=0;a._first_down_up=!0;a.jqueryObj.find(".tdb-search-form").fadeTo(100,1);a.jqueryObj.find(".td_module_wrap").removeClass("tdb-aj-cur-element")},remove_input_focus:function(a){0!==a._last_request_results_count&&
a.jqueryObj.find(".tdb-head-search-form-input").addClass("tdb-head-search-nofocus")},_repaintCurrentElement:function(a){a.jqueryObj.find(".td_module_wrap").removeClass("tdb-aj-cur-element");a._current_selection_index>a._last_request_results_count-1?(a.jqueryObj.find(".tdb-search-form").fadeTo(100,1),a.jqueryObj.find(".tdb-head-search-form-input").removeClass("tdb-head-search-nofocus")):(tdbSearch.remove_input_focus(a),a.jqueryObj.find(".td_module_wrap").eq(a._current_selection_index).addClass("tdb-aj-cur-element"))},
do_ajax_call:function(a){var b=a.jqueryObj.find(".tdb-head-search-form-input").val();""===b?tdbSearch.set_input_focus(a):tdLocalCache.exist("tdb-"+b)?tdbSearch.process_ajax_response(tdLocalCache.get("tdb-"+b),a):jQuery.ajax({type:"POST",url:td_ajax_url,data:{action:"td_ajax_search",module:"tdb_module_search",atts:a.blockAtts,td_string:b,limit:a._resultsLimit},success:function(e,f,c){tdLocalCache.set("tdb-"+b,e);tdbSearch.process_ajax_response(e,a)},error:function(a,b,c){window.console.log(c)}})},
process_ajax_response:function(a,b){var e=b.jqueryObj.find(".tdb-head-search-form-input").val(),f=b.jqueryObj.find(".tdb-aj-search");if(""===e)f.empty();else{var c=jQuery.parseJSON(a);c.td_search_query===e&&(b._current_selection_index=0,b._last_request_results_count=c.td_total_in_list,b._first_down_up=!0,f.html(c.td_data),"undefined"!==typeof window.tdAnimationStack&&!0===window.tdAnimationStack.activated&&(window.tdAnimationStack.check_for_new_items(".tdb-aj-search .td-animation-stack",window.tdAnimationStack.SORTED_METHOD.sort_left_to_right,
!0,!1),window.tdAnimationStack.compute_items(!1)))}},hideAllItems:function(){tdbSearch.items.forEach(function(a){tdbSearch.hide_search_box(a)})}}})();jQuery().ready(function(){tdbSearch.init()});
