---
startDelaySeconds: 0
hostPort: 127.0.0.1:8080
jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:8080/jmxrmi
username: 
password: 
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
rules:
- pattern: ".*"
